version: '3.8'

services:

  qdrant:
    image: qdrant/qdrant:latest
    container_name: rag-qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_storage:/qdrant/storage
    environment:
      - QDRANT__SERVICE__HTTP_PORT=6333
      - QDRANT__SERVICE__GRPC_PORT=6334
      - QDRANT__WEB_UI__ENABLED=true
    networks:
      - rag-network

  # LangFlow para UI de fluxos
  # langflow:
  #   image: langflowai/langflow:latest
  #   container_name: rag-langflow
  #   ports:
  #     - "7860:7860"
  #   environment:
  #     - LANGFLOW_DATABASE_URL=sqlite:///app/langflow.db
  #     - LANGFLOW_AUTO_LOGIN=false
  #   volumes:
  #     - langflow_data:/app/langflow
  #   networks:
  #     - rag-network
  #   depends_on:
  #     - qdrant

volumes:
  qdrant_storage:
  langflow_data:

networks:
  rag-network:
    driver: bridge
